version: '3'
services:
    db:
        build: 
            context: ./db
        environment:
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=your_password_here
            - POSTGRES_DB=tomatos_db
        volumes:
            - "db_data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    web:
        build:
            context: ./web
        command: bash -c "./run.sh"
        volumes:
            - "web_state:/state"
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
    db_data:
    web_state:
