# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomato_name', models.CharField(max_length=200)),
                ('tomato_description', models.TextField()),
                ('tomato_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TomatoColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TomatoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tomato',
            name='tomato_colors',
            field=models.ManyToManyField(to='tomatos.TomatoColor'),
        ),
        migrations.AddField(
            model_name='tomato',
            name='tomato_types',
            field=models.ManyToManyField(to='tomatos.TomatoType'),
        ),
    ]
