# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_colors',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tomato',
            old_name='tomato_types',
            new_name='types',
        ),
    ]
