# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatos', '0003_auto_20170911_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
